FIND_PATH(
	WINE_INCLUDE_DIR
	NAMES windows.h
	PATHS ${WINE_ROOT}/include
)

FIND_LIBRARY(
	WINE_LIBRARY
	NAMES wine
	PATHS ${WINE_ROOT}/lib ${WINE_ROOT}/libs/wine
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	WINE
	DEFAULT_MSG
	WINE_INCLUDE_DIR
	WINE_LIBRARY
)
